server.port=8082

spring.application.name=RestoManager
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=resto_db_user
spring.datasource.password=********
spring.datasource.url=jdbc:postgresql://localhost:5432/resto_db
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect