#!/bin/bash

psql -U postgres -d postgres -f ./sql/01_sessionopts.sql
psql -U postgres -d postgres -f ./sql/role_create.sql
psql -U postgres -d postgres -f ./sql/database_create.sql

psql -U resto_db_user -d resto_db -f ./sql/extension_create.sql
psql -U resto_db_user -d resto_db -f ./sql/usertype_create.sql
psql -U resto_db_user -d resto_db -f ./sql/function_create.sql
psql -U resto_db_user -d resto_db -f ./sql/table_create.sql

psql -U resto_db_user -d resto_db -f ./sql/constraint_pk_create.sql
psql -U resto_db_user -d resto_db -f ./sql/constraint_fk_create.sql
psql -U resto_db_user -d resto_db -f ./sql/functional_data_insert.sql
